better argument parsing, added argument -t for supporting multiple filesystems

diff --git a/lxc-quota b/lxc-quota
--- a/lxc-quota
+++ b/lxc-quota
@@ -22,6 +22,7 @@ die () {
 container=
 size=
 lvm_block=
+type="ext";
 
 while :; do
     case $1 in
@@ -29,24 +30,45 @@ while :; do
             show_help    # Print Usage
             exit
             ;;
+        -t|--type)
+            if [ -z "$2" ]; then
+                die 'missing type parameter'
+            fi
+            type=$2
+            shift
+            ;;
         $1)
-            if [ "$2" ]; then
-                container=$2
-                size=$1
-            else
+            if [ -z "$1" ]; then
+                break;
+            fi
+            printf "$1 xx $2";
+            if [ -z "$2" ]; then
                 die 'ERROR: <size> and <container> arguments expected'
             fi
-            break
+            container=$2
+            size=$1
+            shift
             ;;
         -?*)
             printf 'WARN: Unknown option (ignored): %s\n' "$1" >&2
             ;;
         *)
-            break
+            ;;
     esac
 
     shift
 done
+
+resize_ext () {
+    resize2fs $lvm_block
+    if [ $? -ne 0 ]; then
+            die "filesystem resize failed. note that lv and fs size might be mismatched. exit."
+    fi
+}
+
+resize_xfs () {
+    printf "todo"
+}
 
 container_exists () {
 	c_exists=$(lxc list $1 | awk -v cont=$1 '($2==cont) {print $2}')
@@ -56,7 +78,7 @@ container_exists () {
 	return 1;
 }
 
-container_exists $container
+container_exists $container;
 
 set_lvm_block () {
     lvm_block="/dev/lxc/containers_$container"
@@ -74,8 +96,8 @@ e2fsck -f $lvm_block
 #       echo "e2fsck failed. note that lv and fs size might be mismatched. exit."
 #       exit 17
 
-
-resize2fs $lvm_block
-if [ $? -ne 0 ]; then
-        die "filesystem resize failed. note that lv and fs size might be mismatched. exit."
+if [ "$type" == "ext" ]; then
+    resize_ext;
+elif [ "$type" == "xfs" ]; then
+    resize_xfs;
 fi
